CATEGORY_CACHE_KEY = "category_cache"
CATEGORY_CACHE_TIMEOUT = 60**2

SESSION_CACHE_KEY = "session_cache"
SESSION_CACHE_TIMEOUT = 60**2

EVENT_CACHE_KEY = "event_cache"
EVENT_CACHE_TIMEOUT = 60**2

SESSION_APP_CACHE_KEY = "session_app_cache"
SESSION_APP_CACHE_TIMEOUT = 60**2
