# Generated by Django 3.2.10 on 2021-12-29 02:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_session(apps, schema_editor):
    Session = apps.get_model('eye', 'Session')
    ApplicationSession = apps.get_model('eye', 'ApplicationSession')
    for session in Session.objects.all():
        ApplicationSession.objects.create(
            application_id=session.application_id,
            session_id=session.session_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions',
                                                  to='eye.application')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications',
                                              to='eye.session')),
            ],
        ),
        migrations.RunPython(
            migrate_session,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='session',
            name='application',
        ),
        migrations.AddField(
            model_name='session',
            name='session_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
